//@version=5

// start bb
indicator(shorttitle="NEW BBMA by Boolean", title="NEW BBMA by Boolean", overlay=true, timeframe="", timeframe_gaps=true)

mid_len = input.int(20, minval=1, title="Middle SMA", group="Bollinger Bands")
mid_src = input(close, title="Source", group="Bollinger Bands")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev", group="Bollinger Bands")
bb_offset = input.int(0, "Offset", minval = -500, maxval = 500, group="Bollinger Bands")

basis = ta.sma(mid_src, mid_len)
dev = mult * ta.stdev(mid_src, mid_len)
upper_bb = basis + dev
lower_bb = basis - dev

plot(basis, "Middle", color=#2962FF, offset = bb_offset)
p1 = plot(upper_bb, "Upper", color=#2962FF, offset = bb_offset)
p2 = plot(lower_bb, "Lower", color=#2962FF, offset = bb_offset)
// fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))
// end bb

// start moving average
wma1_len = input.int(5, minval=1, title="WMA 1", group="MA Length")
wma2_len = input.int(5, minval=1, title="WMA 2", group="MA Length")
wma3_len = input.int(10, minval=1, title="WMA 3", group="MA Length")
wma4_len = input.int(10, minval=1, title="WMA 4", group="MA Length")
ema_len = input.int(50, minval=1, title="EMA", group="MA Length")

wma1_src = input(low, title="WMA 1", group="MA Source")
wma2_src = input(high, title="WMA 2", group="MA Source")
wma3_src = input(low, title="WMA 3", group="MA Source")
wma4_src = input(high, title="WMA 4", group="MA Source")
ema_src = input(close, title="EMA", group="MA Source")

wma1_out = ta.wma(wma1_src, wma1_len)
wma2_out = ta.wma(wma2_src, wma2_len)
wma3_out = ta.wma(wma3_src, wma3_len)
wma4_out = ta.wma(wma4_src, wma4_len)
ema_out = ta.ema(ema_src, ema_len)

plot(wma1_out, title="WMA 1", color=#FF00FF)
plot(wma2_out, title="WMA 2", color=color.red)
plot(wma3_out, title="WMA 3", color=color.white)
plot(wma4_out, title="WMA 4", color=color.yellow)
plot(ema_out, title="EMA", color=color.aqua)
// end moving average

// start extreme condition
upper_extreme_condition = wma2_out > upper_bb and close < open and open[1] < close[1]
super_upper_extreme_condition =  wma4_out > upper_bb and close < open and open[1] < close[1]
lower_extreme_condition =  wma1_out < lower_bb and close > open and open[1] > close[1]
super_lower_extreme_condition = wma3_out < lower_bb and close > open and open[1] > close[1]

plotshape(series=upper_extreme_condition, location=location.abovebar, color=color.blue, style=shape.labeldown, title="Upper Extreme", size = size.tiny, text = "Extreme", textcolor=color.white)
plotshape(series=super_upper_extreme_condition, location=location.abovebar, color=color.blue, style=shape.labeldown, title="Super Upper Extreme", size = size.normal, text = "Super Extreme", textcolor=color.white)
plotshape(series=lower_extreme_condition, location=location.belowbar, color=color.blue, style=shape.labelup, title="Lower Extreme", size = size.tiny, text = "Extreme", textcolor=color.white)
plotshape(series=super_lower_extreme_condition, location=location.belowbar, color=color.blue, style=shape.labelup, title="Super Lower Extreme", size = size.normal, text = "Super Extreme", textcolor=color.white)
// end extreme condition

// start MHV condition
upper_mhv_condition = close < open and open < upper_bb and close < upper_bb and close > basis and close > wma1_out and close > wma3_out and close[1] > open[1] and close[1] < upper_bb and close > ema_out
lower_mhv_condition = close > open and open > lower_bb and close > lower_bb and close < basis and close < wma2_out and close < wma4_out and close[1] < open[1] and close[1] > lower_bb and close < ema_out

plotshape(series=upper_mhv_condition, location=location.abovebar, color=color.red, style=shape.triangledown, title="Upper MHV", size = size.tiny, text = "MHV", textcolor=color.red)
plotshape(series=lower_mhv_condition, location=location.belowbar, color=color.green, style=shape.triangleup, title="Lower MHV", size = size.tiny, text = "MHV", textcolor=color.green)
// end MHV condition

// start CSAK condition
csak_buy_condition = close > wma2_out and close > wma4_out and open < basis and close > basis and close < upper_bb and open > lower_bb and low > lower_bb and open < close
csak_sell_condition = close < wma1_out and close < wma3_out and open > basis and close < basis and close > lower_bb and open < upper_bb and high < upper_bb and open > close

plotshape(series=csak_buy_condition, location=location.belowbar, color=color.green, style=shape.triangleup, title="CSAK Buy", size = size.tiny, text = "CSAK", textcolor=color.green)
plotshape(series=csak_sell_condition, location=location.abovebar, color=color.red, style=shape.triangledown, title="CSAK Sell", size = size.tiny, text = "CSAK", textcolor=color.red)
// end CSAK conditiontiny

// start momentum condition
momentum_buy_condition = close > upper_bb and close > ema_out
momentum_sell_condition = close < lower_bb and close < ema_out

plotshape(series=momentum_buy_condition, location=location.abovebar, color=color.green, style=shape.labeldown, title="CSM Buy", size = size.tiny, text = "CSM", textcolor = color.white)
plotshape(series=momentum_sell_condition, location=location.belowbar, color=color.red, style=shape.labelup, title="CSM Sell", size = size.tiny, text = "CSM", textcolor = color.white)
// end momentum condition